# Generated by Django 4.1.6 on 2023-02-08 15:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authServ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='opt',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='code',
            field=models.UUIDField(default=uuid.UUID('2edf2e4b-fc16-4e81-a788-7d2549fe2053')),
        ),
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.UUIDField(default=uuid.UUID('2159995b-02b5-4d1c-8d5f-b3c2061f2894')),
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.UUIDField(default=uuid.UUID('1ff57053-bf51-4af8-afe5-3638f7097b69')),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.UUIDField(default=uuid.UUID('6d5462b7-873d-4151-8d85-1e106aeb8b43')),
        ),
    ]
