# Generated by Django 4.1.6 on 2023-02-09 02:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authServ', '0003_alter_address_code_alter_client_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='code',
            field=models.UUIDField(default=uuid.UUID('512d9bd2-462c-4b04-b6fa-045a964d5e82')),
        ),
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.UUIDField(default=uuid.UUID('8cddc555-7316-4ff9-8a8a-46fe3c87afec')),
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.UUIDField(default=uuid.UUID('086d90e0-ea3c-4b9a-be37-ff66182b8827')),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.UUIDField(default=uuid.UUID('e2855208-e592-4082-9422-0aaaccc26670')),
        ),
    ]
